name: Docker Image CI

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 15 * *"

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        run: |
          docker build . --file Dockerfile --tag albtdev/jenkins:latest
          JENKINS_VERSION=$(docker inspect albtdev/jenkins:latest | sed -n 's/^.*"JENKINS_VERSION=\([0-9.]\+\)".*$/\1/p' | head -n 1)
          echo tag version ${JENKINS_VERSION}
          docker tag albtdev/jenkins:latest albtdev/jenkins:${JENKINS_VERSION}
          docker push albtdev/jenkins:latest
          docker push albtdev/jenkins:${JENKINS_VERSION}
